name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dp-test-lint

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
      - run: go version

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          gofmt: true
