name: Vulnerability check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 14 * * 1'

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
